# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker compose exec <service_name> bash

version: "3.9"
services:
  # Base image containing dependencies.
  base:
    image: eel:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: foxy
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True

  # Developer container
  dev:
    extends: base
    image: eel:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
    volumes:
      - ./src/:/eel/src/:rw
      - ./build/:/eel/build/:rw
      - ./install/:/eel/install/:rw
      - ./log/:/eel/log/:rw
    user: ${USERNAME:-devuser}
    command: sleep infinity

  talker:
    extends: base
    command: ros2 run demo_nodes_cpp talker

  listener:
    extends: base
    command: ros2 run demo_nodes_cpp listener
  
  imu:
    extends: base
    command: ros2 run eel imu --ros-args -p simulate:=true

  motor:
    extends: base
    command: ros2 run eel motor --ros-args -p simulate:=true
  