version: "3"

services:
  eel:
    build:
      context: .
      dockerfile: Dockerfile.humble
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/eel
      - /eel/build/
      - /eel/install/
      - /eel/log/
