# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker compose exec <service_name> bash

version: "3.9"
services:
  # Base image containing dependencies.
  base:
    image: arm64v8/eel:latest
    build:
      # context: .
      # dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: foxy
        ARCH: arm64v8/
      # target: base
    # Interactive shell
    # stdin_open: true
    # tty: true
    # Networking and IPC for ROS 2
    # network_mode: host
    # ipc: host
    # Needed to display graphical applications
    # privileged: true

  talker:
    image: arm64v8/eel-talker:latest

  listener:
    image: arm64v8/eel-listener:latest