version: "3.9"
services:
  imu:
    image: foxpoint/eel:foxy-${CURRENT_ARCHITECTURE}
    command: ros2 run eel imu --ros-args -p simulate:=true
    network_mode: host
    ipc: host

  motor:
    image: foxpoint/eel:foxy-${CURRENT_ARCHITECTURE}
    command: ros2 run eel motor --ros-args -p simulate:=true
