version: "3.9"
services:
  imu:
    image: foxpoint/eel:foxy
    command: ros2 run eel imu
    # stdin_open: true
    # tty: true
    # network_mode: host
    # ipc: host
    # privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

  mqtt_bridge:
    image: foxpoint/eel:foxy
    command: ros2 run eel mqtt_bridge --ros-args -p path_for_config:=/home/ubuntu/fleet/local_certs_and_config/iot_config.json
    volumes:
      - ../../fleet/local_certs_and_config/:/home/ubuntu/fleet/local_certs_and_config/:r

  motor:
    image: foxpoint/eel:foxy
    command: ros2 run eel motor
    privileged: true

  rudder:
    image: foxpoint/eel:foxy
    command: ros2 run eel rudder --ros-args -p pigpiod_host:=pigpiod
    privileged: true
    depends_on:
      - pigpiod

  pigpiod:
    image: zinen2/alpine-pigpiod
    privileged: true
