name: Build & test Eel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    if: always()
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          file: Dockerfile.humble
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs: 
      status: ${{ job.status }}

  notify:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD_CHANNEL }}
          status: ${{ needs.build.outputs.status == 'success' && 'success' || 'failure' }}
          title: "Build & test Eel"
          username: GitHub Actions
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
