name: Test Eel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: make install-py
      - name: Run tests
        run: make test
    outputs: 
      status: ${{ job.status }}

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD_CHANNEL }}
          status: ${{ needs.test.outputs.status }}
          title: "Test Eel"
          username: GitHub Actions
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
